---
- name: Wait connection
  wait_for_connection:
    sleep: 1
    timeout: "30"
- name: copy RPM file
  copy:
    src: ../files/remi-release-7.rpm
    dest: ~/remi-release-7.rpm
  # become: yes
  ignore_errors: true
- name: add repo
  yum:
    name: /root/remi-release-7.rpm
    state: present
- name: add repo2
  shell: "yum-config-manager --enable remi-php74"

- name: install php
  yum:
    name:
    - php
    - php-fpm
    - php-mysqlnd
    state: latest
- name: move www.conf
  copy:
    src: ../templates/www.conf
    dest: /etc/php-fpm.d/www.conf
- name: Start  php-fpm
  service:
    name: php-fpm
    state: started
  # become: yes